# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f85e49fc20d57b135ec5d485b56ad415d839a27ab06fe7d2bfa3256c7fbaa03aa7feebea2148c1918add27136ed7e5d8b03ecedbccdb91b9cda44711cbbcb43

test:
  secret_key_base: 9c545097bdcdc6f652779d2f5ef0fd0591c91dd8bc4b479198ef4fa1675e321688de414c9a3e36703722d24c7b68b635ec0a662909e05dd3c143b31ca3ba3c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
